server:
  port: 8071

spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    data-username: root
    data-password: "000000"

  jpa:
    properties:
      hibernate:
        ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#
#    server:
#      port: 8080
#      servlet:
#        context-path: /
#    spring:
#      datasource:
#        username: root
#        password: 123456
#        url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver





















#server:
#port: 8081
#spring:
#application:
# name: service-product
#datasource:
# driver-class-name: com.mysql.jdbc.Driver
# url: jdbc:mysql:///shop?
#  serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
# username: root
# password: root
#jpa:
# properties:
#  hibernate:
#   hbm2ddl:
#    auto: update
#   dialect: org.hibernate.dialect.MySQL5InnoDBDialect
