server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 将gateway注册到nacos
    gateway:
      discovery:
        locator:
          enabled: true  #让gateway从nacos获取服务信息
      routes:
        - id: product_route
          uri: lb://service-product    #lb指的是负载均衡
#          uri: http://127.0.0.1:8081
          order: 1
          predicates:                          #断言判断条件
            - Path=/product-serv/**
            - Method=POST
            - Age=18,60

          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://shop-order
#          uri: http://127.0.0.1:8091
          order: 1
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1
#     spring.main.web-application-type=reactive  是提出网关和tomcat的关系
#  main:
#    web-application-type: reactive

