server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 将gateway注册到nacos
    gateway:
      discovery:
        locator:
          enabled: true  #让gateway从nacos获取服务信息
      routes:
        - id: product_route
          uri: lb://service-product    #lb指的是负载均衡
#          uri: http://127.0.0.1:8081
          order: 1
          predicates:
            - Before=2019-12-31T23:59:59.789+08:00[Asia/Shanghai]
           #- Age=18,60
#            - Path=/product-serv/**
          #            - Method=POST
          filters:
            - StripPrefix=1

 #第二个服务器
        - id: order_route
          uri: lb://shop-order
#          uri: http://127.0.0.1:8091
          order: 1
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1
#     spring.main.web-application-type=reactive  是提出网关和tomcat的关系
#  main:
#    web-application-type: reactive

